name: Add Random Quote to Profile

on:
  # Trigger on push to main branch
  push:
    branches:
      - main

  # Trigger on every hour (using cron schedule)
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0

  # Allow manual trigger of the workflow
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install necessary dependencies (Python is optional here, just used for scripting if needed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Add a random quote to the profile (README.md)
      - name: Add random quote to profile
        run: |
          # Fetch a random line from quotes.txt
          RANDOM_QUOTE=$(shuf -n 1 quotes.txt)
          
          # Append the random quote with heading to the end of README.md
          echo -e "\n## Random quote of the hour\n> $RANDOM_QUOTE" >> README.md
          
          # Commit and push the change to the repository
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Add random quote of the hour"
          git push origin main
